import T from "T";

const {
  PRIMARY_SKILL,
  SECONDARY_SKILL,
  WORK_LOCATION,
  EMP_MODE,
  STATUS,
  PROJECT,
  PROJECT_MODE,
  AVAILABILITY,
  PROJECT_MANAGER,
  EXPERIENCE,
  DEPARTMENT,
  TECHNOLOGY,
  OS_MANAGER,
  ASSIGNED_TO
} = T;

export const FILTER_OPTIONS = [
  PRIMARY_SKILL,
  SECONDARY_SKILL,
  WORK_LOCATION,
  DEPARTMENT,
  EMP_MODE,
  STATUS,
  PROJECT,
  PROJECT_MODE,
  AVAILABILITY,
  PROJECT_MANAGER,
  `${EXPERIENCE} (In Years)`,
];
export const PRE_SALES_FILTER_OPTIONS = [
  TECHNOLOGY,
  OS_MANAGER,
  ASSIGNED_TO,
  STATUS,
];
